version: "3.7"
services:
  nodejs-express-sederhana:
    build: 
      context: .
      args:
        NODE_ENV: development
    working_dir: /app
    command: npm run dev
    volumes: 
      - ./src/:/app/
    ports:
      - "8080:8080"
